const tarotDeck = [
    // Major Arcana (22 card)
    { id: 'maj00', name: 'The Fool', img: 'card/00.png' },
    { id: 'maj01', name: 'The Magician', img: 'card/01.png' },
    { id: 'maj02', name: 'The High Priestess', img: 'card/02.png' },
    { id: 'maj03', name: 'The Empress', img: 'card/03.png' },
    { id: 'maj04', name: 'The Emperor', img: 'card/04.png' },
    { id: 'maj05', name: 'The Hierophant', img: 'card/05.png' },
    { id: 'maj06', name: 'The Lovers', img: 'card/06.png' },
    { id: 'maj07', name: 'The Chariot', img: 'card/07.png' },
    { id: 'maj08', name: 'Strength', img: 'card/08.png' },
    { id: 'maj09', name: 'The Hermit', img: 'card/09.png' },
    { id: 'maj10', name: 'Wheel of Fortune', img: 'card/10.png' },
    { id: 'maj11', name: 'Justice', img: 'card/11.png' },
    { id: 'maj12', name: 'The Hanged Man', img: 'card/12.png' },
    { id: 'maj13', name: 'Death', img: 'card/13.png' },
    { id: 'maj14', name: 'Temperance', img: 'card/14.png' },
    { id: 'maj15', name: 'The Devil', img: 'card/15.png' },
    { id: 'maj16', name: 'The Tower', img: 'card/16.png' },
    { id: 'maj17', name: 'The Star', img: 'card/17.png' },
    { id: 'maj18', name: 'The Moon', img: 'card/18.png' },
    { id: 'maj19', name: 'The Sun', img: 'card/19.png' },
    { id: 'maj20', name: 'Judgement', img: 'card/20.png' },
    { id: 'maj21', name: 'The World', img: 'card/21.png' },
    // Wands (14 card)
    { id: 'wan01', name: 'Ace of Wands', img: 'card/w1.png' },
    { id: 'wan02', name: 'Two of Wands', img: 'card/w2.png' },
    { id: 'wan03', name: 'Three of Wands', img: 'card/w3.png' },
    { id: 'wan04', name: 'Four of Wands', img: 'card/w4.png' },
    { id: 'wan05', name: 'Five of Wands', img: 'card/w5.png' },
    { id: 'wan06', name: 'Six of Wands', img: 'card/w6.png' },
    { id: 'wan07', name: 'Seven of Wands', img: 'card/w7.png' },
    { id: 'wan08', name: 'Eight of Wands', img: 'card/w8.png' },
    { id: 'wan09', name: 'Nine of Wands', img: 'card/w9.png' },
    { id: 'wan10', name: 'Ten of Wands', img: 'card/w10.png' },
    { id: 'wan_p', name: 'Page of Wands', img: 'card/w11.png' },
    { id: 'wan_k', name: 'Knight of Wands', img: 'card/w12.png' },
    { id: 'wan_q', name: 'Queen of Wands', img: 'card/w13.png' },
    { id: 'wan_K', name: 'King of Wands', img: 'card/w14.png' },
    // Cups (14 card)
    { id: 'cup01', name: 'Ace of Cups', img: 'card/c1.png' },
    { id: 'cup02', name: 'Two of Cups', img: 'card/c2.png' },
    { id: 'cup03', name: 'Three of Cups', img: 'card/c3.png' },
    { id: 'cup04', name: 'Four of Cups', img: 'card/c4.png' },
    { id: 'cup05', name: 'Five of Cups', img: 'card/c5.png' },
    { id: 'cup06', name: 'Six of Cups', img: 'card/c6.png' },
    { id: 'cup07', name: 'Seven of Cups', img: 'card/c7.png' },
    { id: 'cup08', name: 'Eight of Cups', img: 'card/c8.png' },
    { id: 'cup09', name: 'Nine of Cups', img: 'card/c9.png' },
    { id: 'cup10', name: 'Ten of Cups', img: 'card/c10.png' },
    { id: 'cup_p', name: 'Page of Cups', img: 'card/c11.png' },
    { id: 'cup_k', name: 'Knight of Cups', img: 'card/c12.png' },
    { id: 'cup_q', name: 'Queen of Cups', img: 'card/c13.png' },
    { id: 'cup_K', name: 'King of Cups', img: 'card/c14.png' },
    // Swords (14 card)
    { id: 'swo01', name: 'Ace of Swords', img: 'card/s1.png' },
    { id: 'swo02', name: 'Two of Swords', img: 'card/s2.png' },
    { id: 'swo03', name: 'Three of Swords', img: 'card/s3.png' },
    { id: 'swo04', name: 'Four of Swords', img: 'card/s4.png' },
    { id: 'swo05', name: 'Five of Swords', img: 'card/s5.png' },
    { id: 'swo06', name: 'Six of Swords', img: 'card/s6.png' },
    { id: 'swo07', name: 'Seven of Swords', img: 'card/s7.png' },
    { id: 'swo08', name: 'Eight of Swords', img: 'card/s8.png' },
    { id: 'swo09', name: 'Nine of Swords', img: 'card/s9.png' },
    { id: 'swo10', name: 'Ten of Swords', img: 'card/s10.png' },
    { id: 'swo_p', name: 'Page of Swords', img: 'card/s11.png' },
    { id: 'swo_k', name: 'Knight of Swords', img: 'card/s12.png' },
    { id: 'swo_q', 'name': 'Queen of Swords', img: 'card/s13.png' },
    { id: 'swo_K', name: 'King of Swords', img: 'card/s14.png' },
    // Pentacles (14 card)
    { id: 'pen01', name: 'Ace of Pentacles', img: 'card/p1.png' },
    { id: 'pen02', name: 'Two of Pentacles', img: 'card/p2.png' },
    { id: 'pen03', name: 'Three of Pentacles', img: 'card/p3.png' },
    { id: 'pen04', name: 'Four of Pentacles', img: 'card/p4.png' },
    { id: 'pen05', name: 'Five of Pentacles', img: 'card/p5.png' },
    { id: 'pen06', name: 'Six of Pentacles', img: 'card/p6.png' },
    { id: 'pen07', name: 'Seven of Pentacles', img: 'card/p7.png' },
    { id: 'pen08', name: 'Eight of Pentacles', img: 'card/p8.png' },
    { id: 'pen09', name: 'Nine of Pentacles', img: 'card/p9.png' },
    { id: 'pen10', name: 'Ten of Pentacles', img: 'card/p10.png' },
    { id: 'pen_p', name: 'Page of Pentacles', img: 'card/p11.png' },
    { id: 'pen_k', name: 'Knight of Pentacles', img: 'card/p12.png' },
    { id: 'pen_q', name: 'Queen of Pentacles', img: 'card/p13.png' },
    { id: 'pen_K', name: 'King of Pentacles', img: 'card/p14.png' }
];